name: Release

on: 
  push:
    tags:
    - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Config
      run: |
        rustup target add x86_64-pc-windows-gnu x86_64-unknown-linux-musl && \
        sudo apt update -y && \
        sudo apt install gcc-mingw-w64-x86-64 musl musl-tools -y
    - name: Build Linux
      run: cargo build --release --target=x86_64-unknown-linux-musl --all
    - name: Build Windows
      run: cargo build --release --target=x86_64-pc-windows-gnu --all
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/x86_64-unknown-linux-musl/release/smallauncher,target/x86_64-pc-windows-gnu/release/smallauncher.exe"